---
# Parameter configuration file

DEPENDANCES:
    GENERAL:
        BASH: "/usr/bin/bash" # [required] path to bash executable
        RSCRIPT: "/usr/bin/Rscript" # [required] path to Rscript executable
        PERL: "/usr/bin/perl" # [required] path to perl executable
        AWK: "/usr/bin/awk" # [required] path to awk executable
        PYTHON: "/home/m_corentin/Environnements/python3.12/bin/python" # [required] path to python3 executable
    FORMATING:
        PIGZ: "/usr/bin/pigz" # [required] path to pigz executable
        FASTP: "/usr/bin/fastp" # [required] path to fastqc executable
        GTF2BED: "gtfbed" # [required] path to fastqc executable
    QC:
        FASTQC: "/usr/bin/fastqc" # [required] path to fastqc executable
        KMEREXPLOR: "kmerexplor" # [required] path to kermerExplorer executable
        MULTIQC: "/home/m_corentin/Environnements/python3.12/bin/multiqc" # [required] path to multiqc executable
        BAM_STAT: "/home/m_corentin/Environnements/python3.12/bin/bam_stat.py" # [required] path to bam_stat.py executable
        READ_GC: "/home/m_corentin/Environnements/python3.12/bin/read_GC.py" # [required] path to read_GC.py executable
    MAPPING:
        HISAT2:  "hisat2" # [required] path to hisat2 executable
        STAR : "/usr/bin/STAR" # [required] path to STAR; 
        SAMTOOLS: "/usr/bin/samtools" # [required] path to samtools executable
    ANALYSES:
        BEDTOOLS: "/usr/bin/bedtools" # [required] path to bedtools executable
        SPLICELAUNCHER: "/home/m_corentin/Rosa/SpliceLauncher" # [required] path to directory of SpliceLauncher
        GATK: "/home/m_corentin/Bureau/gatk-4.6.1.0/gatk" # [required] path to gatk executable/directory
        BCFTOOLS: "/usr/bin/bcftools" # [required] path to bcftools executable
        BGZIP: "/usr/bin/bgzip"
        FEATURECOUNTS: "featureCounts" # [required] path to featureCounts executable
    VISUALISATION:
        GGSASHIMI: "/usr/bin/ggsashimi.py" # [required] path to ggsashimi.py executable

GENERAL:
        WORKING_DIRECTORY: "data"  # [required] Path to input data tree. Default folder is data
        PREFIX: "library_04_2023_S05_2025"  # [required] Name of run        
        SAMPLES_FILE: "data/metadata/samples_path/library_04_2023_to_S05_2025_test.csv" # [optional] Path to inputs (fastq/bam) files. (ID and paths)
        GENOME:  "Homo_sapiens.GRCh37.dna.primary_assembly.chr.fa"  # [required] path to reference or Name of reference file in working_directory/reference/
        GTF: "gencode.v19.annotation.gtf" # [required] path to gtf Name of gene annotation file in gtf/gff/saf format in working_directory/annotation
        GFF3: "gencode.v19.annotation.gff3" # [required] path to gff3 Name of gene annotation file in gtf/gff/saf format in working_directory/annotation
        MANE: "MANE.to.splicelauncher.txt"  # [required] path to Mane Name of gene annotation file in gtf/gff/saf format in working_directory/annotation
        VCF_KNOWN_SITES: "/home/m_corentin/Rosa/data/1-raw_data/annotation/00-All.chr.vcf.gz"  # [required] path to vcf Name of gene annotation file. I is vcf to genome.
        THREADS: 5 # [required] number of threads use for rules general

USAGE:
    TRIMMING: 1 # [required] 0: Not use trimming rules. 1: Use trimming rules
    QC: 0 # [required] 0: Not use controle quality rules. 1: Use controle quality rules
    MAPPING: 1 # [required] 0: Not use mapping rules. 1: Use mapping rules
    SPLICELAUNCHER: 0 # [required] 0: Not use SpliceLauncher rules. 1: Use SpliceLauncher rules
    VARIANT_CALLING: 1 # [required] 0: Not use variant calling rules. 1: Use variant calling rules

    
TRIMMING:
    THREADS: 5 # [required] number of threads use for rules
    LENGTH: 100 # [required] reads shorted than length_required will be discarded

QUALITY_CONTROLE:
    FASTQC:
        THREADS: 5 # [required] number of threads use for rules
    MULTIQC:
        THREADS: 5 # [required] number of threads use for rules

MAPPING:
    INDEX:
        SJDB_OVERHANG:  # [optional] (int) minimum overhang (i.e. block size) for annotated (sjdb) spliced alignments. Default: 99
        GENOME_SA_SPARSE_D:  # [optional] (int) suffux array sparsity, i.e. distance between indices: use bigger numbers to decrease needed RAM at the cost of mapping speed reduction. 
        RAM:  # [optional] (int) maximum avalable RAM (bytes) for genome generation 
        GENOME_SA_INDEX_NBASES:  # [optional] (int) length (bases) of the SA pre-indexing string. Typically between 10 and 15. Longer strings will use mush more memory, but allow faster searcges. for small genomes, the parammeter -genomeSAindexNbases must be scaled down to min(14, log2(GenomeLength)/2-1)
        THREADS: 12 # [required] number of threads use for rules
    ALIGN:
        OUT_FILTER_MISMATCH_NMAX: 2 # [optional] (int)
        OUT_FILTER_MULTIMAP_NMAX: 1 # [optional] (int)
        OUT_SJ_FILTER_INTRON_MAXVSREADN: 500000 # [optional] (int)
        THREADS: 4 # [required] number of threads use for rules
    

SPLICELAUNCHER:
    ANALYSE:
        GENES_OF_INTEREST: "SLA-DFT-Sureselect-V3.csv" #[optional]
        NB_INTERVALS:  #[optinal] (int)
        MIN_COV: 
        THRESHOLD: 
        TRANSCRIPT_LIST: ""
        REMOVE_OTHER: ""
        BED_OUT: 1
        TXT: 0
        GRAPHICS: 1
    POST_ANALYSE:
        SIGNIGICANT_JUNCTIONS:
            #MIN_READS_SAMPLE: "" #reads minimum in junction for sample. default = 10
            MAX_SAMPLES:  #number max of sample with significant value. default = 2
        UNIQUE_JUNCTIONS:
            MIN_READS_SAMPLE:  #reads minimum in junction for sample. default = 10
            MAX_SAMPLES:  #number max of sample with reads in junction default = 2
    SASHIMI_PLOT:
        USE : 1
        NUMBER_SAMPLES:
        EXTEND_BP: 
        MIN_THRESHOLD_NB_READS:
        COLOR: "/home/m_corentin/Rosa/data/metadata/other/palette.txt"

GATK:
    RECALIBRATE:
        THREADS: 6 # [required] number of threads use for rules
    VARIANT_CALLING:
        LOW_DP: 
        LOW_MQ:
        HIGH_FS:
        LOW_QD:
        HIGHSOR:
        THREADS: 12 # [required] number of threads use for rules
