---
# Parameter configuration file

DEPENDANCES:
    HISAT2:  "hisat2" # [required] path to hisat2 executable
    SAMTOOLS: "samtools" # [required] path to samtools executable
    PIGZ: "pigz" # [required] path to pigz executable
    FASTQC: "fastqc" # [required] path to fastqc executable
    FASTP: "fastp" # [required] path to fastqc executable
    KMEREXPLOR: "kmerexplor" # [required] path to kermerExplorer executable
    MULTIQC: "multiqc" # [required] path to multiqc executable
    FEATURECOUNTS: "featureCounts" # [required] path to featureCounts executable

DATA_INPUTS:
    INPUTS_FILE: "" # [optional] Path to inputs (fastq/bam) files. (ID and paths)
    WORKING_DIRECTORY: "data_input"  # [required] Path to input data tree. Default folder is data_input
    GENOME:  "GRCh37.p13.chr.fa"  # [required] Name of reference file in working_directory/reference/
    ANNOTATION: "GRCh37.p13.SLA.chr.gtf" # [required] Name of gene annotation file in gtf/gff/saf format in working_directory/annotation

PARAMS:
    GENERAL:
        WORKING_DIRECTORY:  ""  # [optional] Path to working directory. Default: in current directory
        PREFIX: "test_250924"  # [required] Name of run
    FILTERFASTQ:
        USE:  0 #[required] 0: Fastq is not filtered (fastp). 1: Fastq is filtered (fastp)
        THREADS: 1  # [required] Maximum number of threads the rule can use
    FASTQC:
        THREADS: 1 # [required] Maximum number of threads the rule can use
    FASTP:
        LENGTH: 100 # [required] reads shorted than length_required will be discarded
        THREADS: 1 # [required] Maximum number of threads the rule can use
    HISAT2:
        THREADS: 1  # [required] Maximum number of threads the rule can use
    SAMTOOLS:
        THREADS: 1  # [required] Maximum number of threads the rule can use
    COMPRESS:
        THREADS: 1 # [required] Maximum number of threads the rule can use
    FEATURECOUNTS:
        THREADS: 1 # [required] Maximum number of threads the rule can use
    KMEREXPLOR:
        THREADS: 1 # [required] Maximum number of threads the rule can use
    MULTIQC:
        THREADS: 1 # [required] Maximum number of threads the rule can use
    MERGING:
        THREADS: 2 # [required] Maximum number of threads the rule can use
